version: '3'
services:
  app:
    build:.
    ports:
      - "5000:5000"
    depends_on:
      - db
      - s3
    environment:
      - DATABASE_URL=sqlite:///images.db
      - S3_BUCKET=my-bucket
      - S3_ACCESS_KEY=my-access-key
      - S3_SECRET_KEY=my-secret-key
  db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
  s3:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=my-access-key
      - MINIO_SECRET_KEY=my-secret-key
      - MINIO_BUCKET=my-bucket
